#Logger
logging:
   #file:
    #path: logs
    #name: logs/dailylogs.log
    #max-history: '30'
    #max-size: 10MB
    
   pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%thread] %-5level %-50logger{40} : %msg%n'
    #rolling-file-name: logs/dailylogs-%d{yyyy-MM-dd}.%i.log
   level:
    ROOT: DEBUG
    org.springframework.web: "error"
    org: "error"